#端口配置
server:
  port: 8080
spring:
  #数据源配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/bills?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      username: root
      password: 123456
      max-active: 20
      max-wait: 5000
      initial-size: 1
      validation-query: select 'X' #验证连接
      enable: true
      #配置监控
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin123
        allow:
        deny:
        url-pattern: /druid/*
  #thymeleaf 模板配置
  thymeleaf:
    cache: false
    enabled: true
  #jackson 配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#配置mybatis-plus
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
    banner: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
